### ISSUE TITLE
Could improve matching based on number of parameters

### ISSUE THREAD

**Issue by AndyRB** [GivePenny/GherkinSpec#28]
Current matching doesn't take into account number of parameters, so in the following example function Test1 is a match for both gherkin When statements:

```
When I submit <value>
When I submit <value1> and <value2>

[When I submit (.*)]
public void Test1(string value)

[When I submit (.*) and (.*)]
public void Test2(string value1, string value2)
```

This is just a suggestion, as the workaround is to use less greedy regex and more specific step definitions.
But would it be worth matching based on number of parameters so that Test2 is preferred to Test1 for the second when statement ("When I submit <value1> and <value2>")?

**Comment by DaveAurionix** [comment]
I like the idea of "being convenient", but I'm still trying to decide if the fault is really in the regex.  For example, it should be `When I submit "<value1>" and "<value2>"` (note the quote marks) with a regex of `[When(@"I submit ""([^""]+)""" and ""([^""]+)""")]`.  A different delimiter character could be chosen.  The point is that this removes the ambiguity from the test itself, which creates safer tests.  What happens if a new test scenario is written where the phrase `and more` is intended to be part of value1 for the Test1 method, but actually the Test2 method would be silently bound and executed due to the missing value delimiter characters (quotes, here) - and due to this magic inside GherkinSpec.

Does GherkinSpec "fail-safe" at the moment with an exception complaining about multiple matching step definitions?

If we silently patch over the ambiguous regular expression, fixing it by magic, then we potentially create confusing scenarios.  One example of this would be if the Test2 method is deleted then suddenly instead of tests failing due to a missing step (logical and expected), the tests would instead flip to execute Test1 with no warning.  Hopefully the tests would still fail, but that would depend on the assertions and test scenario rather than simply because the test step had been deleted (and so the error messages would be less obvious).

I'm tempted to say "won't fix" in order to encourage safer, clearer test steps - but is there a point I've missed?  The intended use-cases for GherkinSpec revolve around removing coding/technical distractions from an agile dev team reviewing a (micro)service's behaviour, e.g. in planning sessions.  Perhaps the demand for natural language outweighs the need for test accuracy and safety by using value delimiter characters?

**Comment by AndyRB** [comment]
@DaveAurionix I think you're right.
I think it just comes down to carefully designed step definitions, and personally I don't think value delimiters detract too much from the readability and are worth it for the improved match accuracy they provide.
Single quotes would suffice in most cases, without complicating the regex either, e.g.: `[When(@"I search for '(.*)'")]`

Having to run through a number of test resolution rules, where different methods may be matched based on their relative precedence will just violate the principle of least astonishment, and be confusing.

One thing you might want to consider is updating the examples to use less greedy regex by default, maybe using delimiters?

Also, yes GherkinSpec did correctly complain about multiple matches.

**Comment by DaveAurionix** [comment]
Good point about the examples. Unfortunately (!) they all use numbers are the moment, which don't suffer from the same problem.  We've updated one of the documentation pages instead.

Commit: https://github.com/GivePenny/GherkinSpec/commit/d8b5acd8611c05c4b9c5ba9bb6bcc0c1180d4a7f
