### ISSUE TITLE
AndAttribute and ButAttribute are not implemented

### ISSUE THREAD

**Issue by AlexTeixeira** [GivePenny/GherkinSpec#38]
Hi Again,

On using the library in a more complexe Scenario, I do not found the **AndAttribute** and **ButAttribute**.

If we follow Gherkin guidelines in cucumber website, **And** and **But** should exist as attribute.

I tried to add the attribute with the following tests, but I do not found where the tests are localized. This is a quite simple changes for someone that already knows the project, so I prefer create this issue :)

**Comment by DaveAurionix** [comment]
Hi Alex,

The `And` and `But` keywords are implemented in the Cucumber syntax, but the C# uses the _context_ that those keywords are used in (which would be either `Given`, `When` or `Then`).  To create step definitions for `And` or `But` steps, you can use the corresponding `[Given]`, `[When]` or `[Then]` C# attributes.

For example, if your `.feature` file contains a snippet like this:
```gherkin
Given some setup step
And another setup step
Then ....
```

Then your C# steps would need these two methods **(note that they both use the Given attribute)**:
```csharp
[Given("some setup step")]
public void GivenSomeSetupStep()
{
}

[Given("another setup step")]
public void GivenAnotherSetupStep()
{
}
```

The Cucumber step that starts with "And" is actually another Given step in disguise (in another test the same step might be re-used and appear as `Given another setup step`).  The C# method shows that and is decorated with a `[Given]` instead of an `[And]` because of that.  It helps people working on the method to remember that the method has Arrange responsibilities (in the language of Arrange-Act-Assert).

For a working example, take a look in the ComplexExample repository.  The Cucumber in this feature contains an `And` step in the third scenario: https://github.com/GivePenny/GherkinSpec.ComplexExample/blob/master/GherkinSpec.ComplexExample.Tests/Features/Addition.feature

The C# step definition for that is here (look at the `[Given]` attribute on the first method): https://github.com/GivePenny/GherkinSpec.ComplexExample/blob/master/GherkinSpec.ComplexExample.Tests/Steps/CalculatorOperationSteps.cs.

I hope that's useful!

Dave.

**Comment by AlexTeixeira** [comment]
Hi,

It was I understood for the test and code that I read yesterday. 
Yes the `[Given]` have the same behavior of `[And] `and `[But]`, this is just different annotation.

But this can be disturbing for a new user of the gherkin language (like me) and can be disturbing too during code reviews.

Is it possible to have a `[AndAttribute]` and a `[ButAttribute]` who inherit from the `[GivenAttribute]` ?

With this solution, you don't break your first attempt to "hide the both attribute" but you let the developers use these two attributes ?

**Comment by DaveAurionix** [comment]
Sadly I don't think `AndAttribute` and `ButAttribute` could inherit from `GivenAttribute` because sometimes `And` and `But` Cucumber keywords are used in the context of a `When` or a `Then`... and we can't inherit from more than one base class at a time.

It's interesting that `And` and `But` can cause initial confusion.  I think that this is because in the Gherkin language they are not like the `Given`, `When` and `Then` attributes, but we try to think of them as if they are the same.  `And` and `But` are different because they might be a `Given` or they might be a `When` or they might be a `Then`.  That's confusing.  They can be many things.

We like that "confusion" in the Gherkin language because it helps us write more natural-language specifications.  We don't want to bring that confusion into C# though, instead we want people to be clear about the purpose of the steps methods that they write so the code is well-written and ideally single-purpose.  Tools like GherkinSpec are designed to help these two worlds meet and work together - the natural-language freedom of the Gherkin language and the clear, tight, predictable, maintainable safety of a programming language (like C#).

Making method-developers concentrate on whether the method is supposed to be setting up test assumptions (Given, or arrange), or whether the method is performing work (When, or act) or whether it is checking or verifying something (Then, or assert) we think helps people create higher quality step definitions.  To help them, we want to avoid the "syntactic sugar" of `And` and `But` because they don't describe what the method is for.  We want to keep those terms isolated to the Gherkin language where it is very obvious from the context what they mean (because they appear on lines immediately after a Given, a When or a Then).

We can either confuse people by creating "AndAttribute" and "ButAttribute" classes and then the methods they are decorated with are confusingly labelled, or we can confuse people by not creating those attributes and they have to hunt around to learn that GherkinSpec needs "GivenAttribute", "WhenAttrribute" or "ThenAttribute" classes to be used.  Out of the two confusing options, we help people write better test step code if we don't support those attributes at the moment, so we think that is the better option out of the two.

**Comment by AlexTeixeira** [comment]
This is a very good explanation and I understand your mindset. I think a little sentence in Readme can be useful to avoid this kind of question.

Thanks for your time and explanation.

**Comment by DaveAurionix** [comment]
Thanks Alex - PR with docs update should be merged in tomorrow.
