### ISSUE TITLE
Very original Name xD

### ISSUE THREAD

**Issue by arekbal** [GivePenny/GherkinSpec#42]
Dude, you really couldn't come up with more original name?
Single search would have saved the mankind. 🗡 
That is just ridiculous. 🥇 

My project: [GherkinSpec](https://github.com/arekbal/GherkinSpec)
My nugets:
[GherkinSpec.Core](https://www.nuget.org/packages/GherkinSpec.Core) [GherkinSpec.NUnit](https://www.nuget.org/packages/GherkinSpec.NUnit) [GherkinSpec.MsTest](https://www.nuget.org/packages/GherkinSpec.MsTest) [GherkinSpec.XUnit](https://www.nuget.org/packages/GherkinSpec.XUnit)
Both initiatives (yours, mine) are dotnet...

I am not even mad. 😅 
Just tell me how it happened.

**Comment by DaveAurionix** [comment]
Hi,

GherkinSpec was an investment of effort that we didn't start lightly.  We had been very fond of SpecFlow for many years but SpecFlow had been taking far too long to port their code to .NET Standard (more than eighteen months at the time).  We felt that was probably due to bloat that we didn't need or want.  Reluctantly we began writing our own project from scratch (we'd much rather have contributed to something already out there).

At the time, we searched GitHub for replacements for SpecFlow and didn't find anything suitable.  We didn't find your project, for example.  Before uploading the first draft to GitHub we found the name that we had taken clashed with an existing project so we renamed it.  A while after uploading that first draft we found the second name also clashed so we renamed it again (IIRC there should be a rename commit early in the commit history on GitHub).  This change to a third name was rushed and we missed your project (rushed because of an awareness of the safety provided by the "namespaces" principle - which we'll come on to in a moment).  We did later become aware of your project but by then many of our internal solutions had tests that referenced GivePenny.GherkinSpec, so we decided not to introduce a fourth name as it was just getting silly.

The problem is that when writing any test adapter for the Gherkin Specification Language, the phrase "GherkinSpec" is an extremely obvious shortened form and several alternatives are also already used.  

GitHub is now a very large place and the English language is getting smaller every day.  These accidental conflicts are all part of being part of a wider open code community that is encouraged to contribute, to clone, and to fork, e.g. to keep a core idea such as Gherkin alive as a Specification Language.

Our packages are always prefixed with the organisation's name, e.g. "GivePenny.GherkinSpec".  It's clear to people that this is a project supported by an organisation and is separate to other projects.  This company name prefix is a very common concept - in .NET namespaces for example - and its purpose is to create a "naming space" where names can be unique and not conflict with the same terms used in other namespaces, e.g. by other organisations (or individuals, in this case).  This is a core concept of .NET code (almost every C# file will reference or define nested namespaces) and is a long-established practice when publishing packages containing that code.

Please feel free to take any ideas, concepts or code that you want from our project, or even to entirely fork it and build on it under your own name.  That's what GitHub is for and we're more than happy to share.  We'd be overjoyed to see this project superceded by something better and we look forward to the day when we can stop using this our own attempt.

Dave
